### PR TITLE
fix: use playground image based on llama-cpp-python

### LINKED ISSUE #139: Replace localAI by llama-cpp-python
Image is available at quay.io/bootsy/playground:v0

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #139

### CODE REVIEW

**Comment by feloy** [comment]
I get an unauthorized access when I try to pull the image quay.io/bootsy/playground:v0

**Comment by feloy** [comment]
It seems that we get only the beginning of the response from the model

model-begin

**Comment by jeffmaury** [comment]
Need to verify with a curl request

**Comment by feloy** [comment]
The reply does not contain anything indicating there will be a suite.

Is it an internal problem in the container, or are we using the good request?

reply

**Comment by feloy** [comment]
Yes, that works for me now. 
The container gets more time to start now, I have created a related issue: https://github.com/projectatomic/studio-extension/issues/147

**Review by feloy — APPROVED** [review]

**Review by lstocchi — APPROVED** [review]
Super slow on windows and the answer is not really the one i expected but it works 😅 

image

**Pull request merged**
